use crate::utils::apps::help_guide::HelpSection;

pub fn get_help_sections() -> Vec<HelpSection> {
    vec![
        HelpSection {
            title: "1. Introduction".to_string(),
            content: vec![
                "Welcome to the `A.R.C.S. Emulator`!".to_string(),
                " ".to_string(),
                "A.R.C.S. stands for `Advanced RISC-like Computer System`.".to_string(),
                "It is a 16-bit CPU architecture designed for educational purposes.".to_string(),
                "This project provides a complete ecosystem for writing, assembling, and running programs for the A.R.C.S. CPU.".to_string(),
                " ".to_string(),
                "Features:".to_string(),
                "- A complete instruction set with support for arithmetic, logic, memory, and control flow.".to_string(),
                "- A two-pass assembler with support for labels, directives, and macros.".to_string(),
                "- An interactive TUI with a text editor, file explorer, and emulator.".to_string(),
                "- A memory-mapped I/O system for text-based input and output.".to_string(),
                "- Support for breakpoints for debugging.".to_string(),
                " ".to_string(),
                "Use the `left` and `right` arrow keys to navigate between sections.".to_string(),
                "Use the `up` and `down` arrow keys to scroll through the content.".to_string(),
            ],
        },
        HelpSection {
            title: "2. The A.R.C.S. CPU".to_string(),
            content: vec![
                "The A.R.C.S. CPU is a 16-bit RISC-like processor.".to_string(),
                "It has a simple and clean architecture, making it easy to learn and program.".to_string(),
                " ".to_string(),
                "`Registers`".to_string(),
                "The CPU has the following 32-bit registers:".to_string(),
                "- `AX`, `BX`, `CX`, `DX`, `EX`, `FX`, `GX`, `HX`: General-purpose registers.".to_string(),
                "- `SP`: Stack Pointer.".to_string(),
                "- `BP`: Base Pointer.".to_string(),
                "- `SI`: Source Index.".to_string(),
                "- `DI`: Destination Index.".to_string(),
                "- `PC`: Program Counter.".to_string(),
                "- `FLAGS`: Flag register.".to_string(),
                " ".to_string(),
                "`Flags`".to_string(),
                "The `FLAGS` register contains the following flags:".to_string(),
                "- `carry` (bit 0): Set if an arithmetic operation generates a carry.".to_string(),
                "- `zero` (bit 6): Set if the result of an operation is zero.".to_string(),
                "- `sign` (bit 7): Set if the result of an operation is negative.".to_string(),
                "- `interrupt` (bit 9): Enables or disables interrupts.".to_string(),
                "- `string` (bit 10): Used for string operations.".to_string(),
                "- `overflow` (bit 11): Set if an arithmetic operation results in an overflow.".to_string(),
                "- `macro` (bit 12): Used by the assembler.".to_string(),
                "- `stack_dir` (bit 13): Controls the stack direction (0 for downwards, 1 for upwards).".to_string(),
            ],
        },
        HelpSection {
            title: "3. Memory Layout".to_string(),
            content: vec![
                "The A.R.C.S. has a 64KB address space (0x0000 to 0xFFFF).".to_string(),
                "The memory is organized into the following sections:".to_string(),
                " ".to_string(),
                "- `Text Section` (0x0000 - 0x7FFF): Stores the program code.".to_string(),
                "- `Data Section` (0x8000 - 0xDFFF): Stores program data.".to_string(),
                "- `I/O Region` (0xE000 - 0xEFFF): Used for memory-mapped I/O.".to_string(),
                "- `Stack` (0xF000 - 0xFFFF): Used for the call stack.".to_string(),
            ],
        },
        HelpSection {
            title: "4. Instruction Set".to_string(),
            content: vec![
                "The A.R.C.S. instruction set is small and easy to learn.".to_string(),
                "Instructions are grouped by category:".to_string(),
                " ".to_string(),
                "`Data Transfer Instructions`".to_string(),
                "- `MOVI DST, SRC`: Move immediate value to register.".to_string(),
                "- `MOVW DST, SRC`: Move word value to register.".to_string(),
                "- `LODI DST, SRC`: Load immediate value.".to_string(),
                "- `LODW DST, SRC`: Load word from memory.".to_string(),
                "- `STRI DST, SRC`: Store immediate value to memory.".to_string(),
                "- `STRW DST, SRC`: Store word to memory.".to_string(),
                "- `PUSH SRC`: Push value onto the stack.".to_string(),
                "- `POP DST`: Pop value from the stack.".to_string(),
                "- `XCGH OP1, OP2`: Exchange values.".to_string(),
                " ".to_string(),
                "`Arithmetic Instructions`".to_string(),
                "- `ADDW DST, SRC`: Add word.".to_string(),
                "- `SUBW DST, SRC`: Subtract word.".to_string(),
                "- `MUL DST, SRC`: Multiply word.".to_string(),
                "- `INC DST`: Increment word.".to_string(),
                "- `DEC DST`: Decrement word.".to_string(),
                "- `NEG DST`: Negate word.".to_string(),
                " ".to_string(),
                "`Bitwise Instructions`".to_string(),
                "- `AND DST, SRC`: Bitwise AND.".to_string(),
                "- `OR DST, SRC`: Bitwise OR.".to_string(),
                "- `XOR DST, SRC`: Bitwise XOR.".to_string(),
                "- `NOT DST`: Bitwise NOT.".to_string(),
                " ".to_string(),
                "`Control Flow Instructions`".to_string(),
                "- `CMPW OP1, OP2`: Compare word.".to_string(),
                "- `JMP ADDR`: Jump to address.".to_string(),
                "- `CALL ADDR`: Call subroutine.".to_string(),
                "- `RET`: Return from subroutine.".to_string(),
                "- `JE ADDR`: Jump if equal.".to_string(),
                "- `JNE ADDR`: Jump if not equal.".to_string(),
                "- `JGT ADDR`: Jump if greater than.".to_string(),
                "- `JGE ADDR`: Jump if greater than or equal.".to_string(),
                "- `JLT ADDR`: Jump if less than.".to_string(),
                "- `JLE ADDR`: Jump if less than or equal.".to_string(),
                "- `JS ADDR`: Jump if sign.".to_string(),
                "- `JCO ADDR`: Jump if carry or overflow.".to_string(),
                " ".to_string(),
                "`I/O Instructions`".to_string(),
                "- `IN DST`: Read from input device.".to_string(),
                "- `OUT SRC`: Write to output device.".to_string(),
                " ".to_string(),
                "`System Instructions`".to_string(),
                "- `HALT`: Halt the CPU.".to_string(),
                "- `SETF FLAG`: Set a flag.".to_string(),
                "- `CLRF FLAG`: Clear a flag.".to_string(),
            ],
        },
        HelpSection {
            title: "5. Assembler Directives".to_string(),
            content: vec![
                "The assembler supports the following directives:".to_string(),
                " ".to_string(),
                "- `.text`: Marks the beginning of the text section.".to_string(),
                "- `.data`: Marks the beginning of the data section.".to_string(),
                "- `.word VALUE`: Allocates a 32-bit word.".to_string(),
                "- `.byte VALUE`: Allocates a byte.".to_string(),
                "- `.string \"STRING\"`: Allocates a string.".to_string(),
                "- `label: .equ VALUE`: Defines a constant.".to_string(),
                "- `.align BOUNDARY`: Aligns the current address to a boundary.".to_string(),
                "- `.space SIZE`: Reserves a block of memory.".to_string(),
            ],
        },
        HelpSection {
            title: "6. Writing A.R.C.S. Code".to_string(),
            content: vec![
                "Here is an example of a simple A.R.C.S. program that prints \"Hello, World!\" to the output device:".to_string(),
                " ".to_string(),
                "`.text`".to_string(),
                "`    LODI AX, hello_msg`".to_string(),
                "`    OUT AX`".to_string(),
                "`    HALT`".to_string(),
                " ".to_string(),
                "`.data`".to_string(),
                "`hello_msg: .string \"Hello, World!\\n\"`".to_string(),
            ],
        },
    ]
}